-------
# Group 1 Project
Title: "RMED901_Group1_Project_110923"
Authors: "Marianne Bråtveit, Eline Hillestad, Ryan Dunkel and Jonathan Chambenoit"
Date: "2023-09-11"
Output: html_document

-----
#Day 5 - Reading, exploring, tidying and exploring data

#Importing packages
```{r}
library(tidyverse)
library(here)

here()
data <- read_delim(here("Data", "exam_data.txt")) #Assigning the dataset 
data

```

#Tidying data 
```{r}
data <- data %>% rename(BMI = "BMI kg/m2", #renaming columns 
                Attempts = "# attempts",
                Failures = "# failures")
```

#Checking for duplicates

```{r}
data <- data %>%
  distinct()

```

#checking for numbers or spaces in columns

```{r}
data <- data %>% rename(BMI = "BMI kg/m2", #renaming columns 
                Attempts = "# attempts",
                Failures = "# failures") %>% 
  distinct() %>% #removing duplicates
  pivot_wider(names_from = difficulties_intubating_feature, 
              values_from = difficulties_intubating_value) %>% 
  #Creating three new columns by pivoting wider 
  separate(col = last_method_S_F,
           into = c("last_method", "last_method_S_F"),
           sep = "_") %>% #Splitting the last_method_S_F column into two different columns
  mutate(last_method_S_F = as.double(last_method_S_F),
         last_method = as.double(last_method)) #converting these two columns to numeric columns as they were turned into character columns when splitting them
  
```
